Components/CartSummaryViewComponent.cs
using IS413_Amazon_A5_ZS.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IS413_Amazon_A5_ZS.Components
{
    //Have the CartSummaryViewComponent inherit from the ViewComponent class
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        //Constructor that sets the private cart variable to the passed-in value
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<!--Import Book Model to be accessed for the rest of the dynamically created page-->
@model Book

<!--Dynamically input appropriate values from each Book entry by reference to the database-->
<tr id="highlight">
    <td>@Model.BookId </td>
    <td>@Model.Title</td>
    <td>@Model.Author_First_Name</td>
    <td>@Model.Author_Middle_In</td>
    <td>@Model.Author_Last_Name</td>
    <td>@Model.Publisher</td>
    <td>@Model.ISBN</td>
    <td>@Model.Classification</td>
    <td>@Model.Category</td>
    <td>$@Model.Price</td>
    <td>@Model.Page_Num</td>
    <!--Code that displays the buy button that adds an item to the user's current cart session-->
    <td>
        <form id="@Model.BookId" asp-page="/BookPurchase" method="post">
            <input type="hidden" asp-for="BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                @*@Model.Title*@
                <button type="submit" class="btn-success btn-sm pull-right">
                    Buy Book
                </button>
            </span>
        </form>
    </td>
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
Zachary Sterling
IS 413 Section 3 Group 4
Description: Webpage that displays dynamic book information from a database in the form of a stylized table.

    Additional styling from bootstrap: in the table tag: table-striped table-bordered table-hover table-light.
        In the navigation buttons: bg-info btn-dark.
-->
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IS413_Amazon_A5_ZS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <!--Code that displays the shopping cart and the site's main name at the top of the page-->
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand">Buy Books Inc.</div>
                    <div class="col navbar-brand">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </div>
                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!--Added col-12 class to make table full length-->
    <div class="container col-12">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Buy Books Inc.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>