Components/NavigationMenuViewComponent.cs
using IS413_Amazon_A5_ZS.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IS413_Amazon_A5_ZS.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookRepository _repository;

        //set the private _repository variable when this object is first loaded
        public NavigationMenuViewComponent (IBookRepository r)
        {
            _repository = r;
        }

        public IViewComponentResult Invoke()
        {
            //Store the currently selected category that is present in the URL in the viewbag to dynamically highlight the button for the current
            //category
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(_repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Controllers/HomeController.cs
using IS413_Amazon_A5_ZS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using IS413_Amazon_A5_ZS.Models.ViewModels;

namespace IS413_Amazon_A5_ZS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        //Create a private repository from IBookRepository
        private IBookRepository _repository;

        //Determines how many book items are displayed per page
        public int ItemsPerPage = 5;

        //Constructor for the HomeController, that mainly sets a few private variables with parameters
        public HomeController(ILogger<HomeController> logger, IBookRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        //Return the index/home page that queries the appropriate number of books as well as allows filters
        public IActionResult Index(string category, int pageNum = 1)
        {
            return View(new BookListViewModel
                //Query to get the correct book information for each page
                {
                    Books = _repository.Books
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.BookId)
                .Skip((pageNum - 1) * ItemsPerPage)
                .Take(ItemsPerPage)
                ,
                //Modify certain attributes of the PagingInfo object in the BookListViewModel class
                PagingInfo = new PagingInfo
                    {  
                        CurrentPage = pageNum,
                        ItemsPerPage = ItemsPerPage,

                        //If statement to determine the correct number of page options that is displayed under the table
                        TotalNumItems = category == null ? _repository.Books.Count() :
                            _repository.Books.Where(x => x.Category == category).Count()
                    },
                CurrentCategory = category
                }
            );
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Buy Books!";
}

@model BookListViewModel

<!--Title Text for Page-->
<div class="text-center col-12">
    <h1 class="display-4">Buy Books!</h1>
    <h3 class="modal-title text-dark bg-info font-weight-bold">Filter By Category Below</h3>
</div>

<br />
<!--Import information for the category filter options-->
<div class="col-12 text-center">
    <vc:navigation-menu />
</div>

<br />
 
<!--Table for all books to be listed-->
<div class="text-center col-12">
    <div class="text-center">
        <table class="center table table-striped table-bordered table-hover table-info">
            <thead>
                <tr>
                    <th>Book ID</th>
                    <th>Title</th>
                    <th>Author First Name</th>
                    <th>Author Middle Initial</th>
                    <th>Author Last Name</th>
                    <th>Publisher</th>
                    <th>ISBN</th>
                    <th>Classification</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Page Count</th>
                </tr>
            </thead>

            <tbody>
                <!--Loops through all of the submitted restaurants to print them out here.-->
                <!--Information to loop through is located in a seperate .cshtml file called BookSummary.cshtml, which is imported into here-->
                @foreach (var x in Model.Books)
                {
                    <partial name="BookSummary" model="x" />
                }
            </tbody>
        </table>
    </div>
</div>

<!--page navigation numbers, with added styling features-->
<div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true" page-class="btn" 
     page-class-normal="btn-outline-dark"
     page-class-selected="btn-dark"
     page-url-category="@Model.CurrentCategory"
     class="text-center bg-info">
</div>