Pages/BookPurchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IS413_Amazon_A5_ZS.Infrastructure;
using IS413_Amazon_A5_ZS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IS413_Amazon_A5_ZS.Pages
{
    public class BookPurchaseModel : PageModel
    {
        private IBookRepository _repository;

        //Constructor that sets the private repository variable
        public BookPurchaseModel (IBookRepository repo, Cart cartService)
        {
            _repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }

        //Methods

        //Set the returned URL to what is passed in, and if the passed in parameter is null then set the returned URL as a single /
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = _repository.Books.FirstOrDefault(predicate => predicate.BookId == bookId);

            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.AddItem(book, 1);

            //HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        //Method that helps remove items from the user's cart
        public IActionResult OnPostRemove(long bookID, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookId == bookID).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/BookPurchase.cshtml
@page
@model IS413_Amazon_A5_ZS.Pages.BookPurchaseModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">

    <!--Column headers-->
    <thead>
        <tr>
            <th>Title</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <!--Table Body that displays rows of purchased books and their information-->
    <tbody>
        @foreach(var line in Model.Cart.Lines)
        {
        <tr>
            <td>@line.Book.Title</td>
            <td>@line.Quantity</td>
            <td>@line.Book.Price</td>
            <td>@((line.Book.Price * line.Quantity).ToString("c"))</td>
            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookId"
                           value="@line.Book.BookId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>

    <!--Footer that displays the grand total-->
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Grand Total:</td>
            <td>@Model.Cart.ComputeTotalSum().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<!--Button that displays a button that allows the user to go back to the website's main shopping page-->
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>